#映射端口 yaml文件格式区别properties一定注意
server:
  port: 80
#配置日志输出级别
logging:
  level:
    com.its: debug
#    org.springframework: debug

#HiKariCP连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tieba?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  #注意因为我们使用static和templates两个文件夹，所以覆盖配置一下
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/,classpath:/static/*, classpath:/public/, classpath:/templates/*,classpath:/templates/
  #Java热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  #网页热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

#Mybatis配置信息
mybatis:
  #扫描别名
  type-aliases-package: com.its.po
  #mapper文件位置，如果使用通用mapper直接注掉
  #mapper-locations: mappers/*.xml


